config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/links' => 'welcome#links'
  get '/archives' => 'welcome#archives'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
        @article = Article.new
    end

    def create
        @article = Article.new article_params
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    def show
        @article = Article.find params[:id]
    end
private
    def article_params
        params.require(:article).permit(:title,:content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles  = Article.all
  end

  def about
  end

  def links
  end
  
  def archives
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
 <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper">
      <article class="page">
  <div class="post-content">
   <%= form_for :article, url: articles_path do |f| %>
   <% if @article.errors.any? %>
   <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label "标题" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label "内容" %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit "保存" %>
  </p>
<% end %>
    
  </div>
</article>


</div></div>
    <div class="clearfix"></div>
  </div>

app/views/articles/show.html.erb
 <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper"><article class="page">
  <div class="post-content">
      <header><h1><%= @article.title  %></h1></header><br>
      <p>
        <%= @article.content %>
      </p>
  </div>
</article>


</div></div>
    <div class="clearfix"></div>
  </div>

app/views/layouts/_header.html.erb
 <header id="header"><div class="meta inner">
  <h1><a href="/">SimpleBlog</a></h1>
  <nav id="main-nav">
    <ul>
      <li><a href="/about">关于我</a></li>
      <li><a href="/archives">文章归档</a></li>
      <li><a href="/links">友情链接</a></li>
    </ul>
    <div class="clearfix"></div>
  </nav>
</div>
<div class="clearfix"></div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
 <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper"><article class="page">
  <div class="post-content">
    <header>
      <h1>关于我</h1>
      <br>
      <p>
        this is sllt blog.
      </p>
    </header>
    
  </div>
</article>


</div></div>
    <div class="clearfix"></div>
  </div>

app/views/welcome/archives.html.erb
archives.html.erb

app/views/welcome/index.html.erb
 <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper">
      <% @articles.each do |article| %>
    <article class="page">
  <div class="post-content">
    <header><h1><%= link_to article.title, article_path(article) %></h1></header><br>
    <p><%= article.content %></p>
  </div>
</article>
  <% end %>

</div></div>
    <div class="clearfix"></div>
  </div>

app/views/welcome/links.html.erb
 <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper">
      <article class="page">
  <div class="post-content">
    <header>
      <h1>友情链接</h1>
      <br>
      <p>
        <ul>
            <li> <a href="http://snowy.in">Snowy</a></li>
        </ul>
       
      </p>
    </header>
    
  </div>
</article>


</div></div>
    <div class="clearfix"></div>
  </div>